# Setup
title: Obsidian
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# About
description: > # this means to ignore newlines until "baseurl:"
  Obsidian Project goal is to create an inclusive asset sharing platform for 
  small farmers around the world.

# Author
email: edson_alcala@msn.com
twitter_username: EdsonAlcala
github_username:  EdsonAlcala

# Build settings
markdown: kramdown
theme: minima

# Gems
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
